Create Admin Account
Nasser-Eddin-Nasser/Digitact pull request #77
Opened 2020-06-19 08:37 UTC by Nasser-Eddin-Nasser

2020-06-19 11:27 UTC, vishwasanavatti requested changes
Tested locally. I could able to create an account but was not able to login. Could you check the issue?

2020-06-19 11:27 UTC, vishwasanavatti commented on HR-Monitor/hr-monitor.properties
> +javac2.instrumentation.includeJavaRuntime=false
what is this file for? why are paths hard coded?

2020-06-19 11:51 UTC, Nasser-Eddin-Nasser commented on HR-Monitor/hr-monitor.properties
> +javac2.instrumentation.includeJavaRuntime=false
It's for the Ant builder, it should be in git ignore I guess :)

2020-06-19 12:14 UTC, vishwasanavatti approved these changes
Tested again after changes and its works fine. Good work @Nasser-Eddin-Nasser, its perfectly done. All the basic functionalities are included. Can be merged.

2020-06-21 08:34 UTC, dalex135 approved these changes
Ran and tested. Well done. Quality code. :)
Was easy to merge with the US 42.

2020-06-21 08:37 UTC, merged

2020-06-21 11:25 UTC, MBuchalik commented
Are you storing the password in cleartext in the database? If so, I'd recommend to maybe create an Issue here on GitHub that we should change it to use a salted hash. (I'd recommend to use not only a hash, but also to add a salt to it.)